### ISSUE TITLE
can you tell me how you optimized the dlib ?

### ISSUE THREAD

**Issue by 9crk** [gicheonkang/Fast-Face#1]
can you tell me how you optimized the dlib ?
will you provide the source code?

**Comment by gicheonkang** [comment]
Hi, here are the concept applied in this project

1. multi-threaded dlib
2. lower number of pyramidal layer

I will send you a source code asap :)

2017. 5. 25. 오후 12:21에 "周华" <notifications@github.com>님이 작성:

**Comment by 9crk** [comment]
lower number of pyramidal layer

does that means doing face detection?

now my porblem is mainly on landmark predictor part.it's quiet slow.about 150-200ms.

 I don't know why..

**Comment by 9crk** [comment]
https://github.com/davisking/dlib/issues/604
this is the process I did.
I use the code of dlib version 19.1 because I cant get through the version 19.4 on simd part's compile.

**Comment by 9crk** [comment]
I found the solution,...I should build the project in release mode..

**Comment by 9crk** [comment]
now it turns 15ms for landmark.

**Comment by gicheonkang** [comment]
Good work !

Actually, predicting landmark points is not a time-consuming work because dlib supports it.

If you want to make a fast face predictor, you have to reduce the time cost of detecting faces.

That’s a critical part :)

There are many ways to optimize the application, such as resizing the image, making a grayscale image, using a NEON architecture, Compiling release mode ...

You did it on Android platform ?

**Comment by 9crk** [comment]
yes,on Android device.
did you integrated the NEON support ?
I use the 19.1 source code of dlib, because I cant compile the 19.4 through.the simd fils always get errors.

I use the opencv to do face detection, I can optimize it to under 10ms and still usable.

**Comment by 9crk** [comment]
did you eat 粽子 these days btw? :-)

**Comment by gicheonkang** [comment]
Hi, 周华
I’m looking for the ways to port android-version(NEON support)

@fastfastball said that he did it !
Here is the repo https://github.com/fastfastball/dlib_for_arm <https://github.com/fastfastball/dlib_for_arm>

But, when I replace original one(19.1) with new one(19.4, simd). Error occurs.
Maybe it needs to be setting the Android.mk,  Application.mk file

Test it !
If you successfully compiled, please let me know asap :)

Thank you.
