### ISSUE TITLE
face recognition

### ISSUE THREAD

**Issue by omis76** [gicheonkang/Fast-Face#10]
have you tried to make .so file for face recognition using this dlib_face_recognition_resnet_model_v1 model

**Comment by weank1984** [comment]
@omis76 I‘m trying to make a face verify app by using dlib and now it's just able to run. If you're intersted, 
[face recognition ](https://github.com/weank1984/face-recognition.git) And It is still far from finished.

**Comment by omis76** [comment]
thanks @weank1984 , i will look into your app

**Comment by gv22ga** [comment]
[dlib-face-recognition-android](https://github.com/gv22ga/dlib-face-recognition-android)
