### ISSUE TITLE
Optimize the jni native code

### ISSUE THREAD

**Issue by weank1984** [gicheonkang/Fast-Face#11]
Hi, 
I'm trying to optimize face detection. 
Can you open source your Dlib-android source code ? 
Thank you! btw, Happy New Year! 

ps: Here is my email address [weank1984@gmail.com](weank1984@gmail.com). Thanks again.

**Comment by mrka124** [comment]
You can find jni native code in [dlib-android](https://github.com/tzutalin/dlib-android)

**Comment by ldima** [comment]
I compiled https://github.com/tzutalin/dlib-android and tried with this android app.
Result - Face will recognize after 130-150 ms.
Original .so - face will recognize after 50-60 ms.

Where could I find sources this faster dlib .so ?
Thanks.

**Comment by ldima** [comment]
@gicheonkang Hi, help us, please.

**Comment by gicheonkang** [comment]
@ldima Hi, Faster source code on [optimise source](https://github.com/fastfastball)
above source is almost same with mine.

Here are issues that you can tackle. Test and Enjoy !
1. Neon Supported dlib
2. Lower the pyramidal layers
