### ISSUE TITLE
Why MainActivity_ ?

### ISSUE THREAD

**Issue by AntonioVitiello** [gicheonkang/Fast-Face#12]
Hello Gicheon Kang, 
why in your app\src\main\AndroidManifest.xml have 
<activity android:name=".MainActivity_"
and not 
<activity android:name=".MainActivity" ?

**Comment by w568w** [comment]
I suppose it's using [androidannotations](https://github.com/androidannotations/androidannotations),which requests replacing `Activity` with `Activity_`.
