### ISSUE TITLE
How to select only lip's landmarks

### ISSUE THREAD

**Issue by nimesh7424** [gicheonkang/Fast-Face#16]
I am developing makeup app in android so I want to ask that how do i select only lip's landmark and fill color inside like(Lipstick)

**Comment by kartk** [comment]
See the 68 Point landmarks picture in the following link : https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/

As seen from the pic, lips landmarks are from 49 - 68

**Comment by nimesh7424** [comment]
yes you are right.
Actualy I did this but in this library they are not providing a method by which i can get index of particular landmark.
As below code i am not able to get landmark 49 to 68.


if (results.size() != 0) {
    for (final VisionDetRet ret : results) {
        float resizeRatio = 4.5f;
        Canvas canvas = new Canvas(mInversedBipmap);

        // Draw landmark
        ArrayList<Point> landmarks = ret.getFaceLandmarks();
        for (Point point : landmarks) {
            int pointX = (int) (point.x * resizeRatio);
            int pointY = (int) (point.y * resizeRatio);
            canvas.drawCircle(pointX, pointY, 4, mFaceLandmardkPaint);
        }
     }
}

**Comment by kartk** [comment]
May be not the best way but this works :

```
int counter = 0 ;
ArrayList<Point> landmarks = ret.getFaceLandmarks();
    for (Point point : landmarks) {
       if( counter >= 48) {
           int pointX = (int) (point.x * resizeRatio);
           int pointY = (int) (point.y * resizeRatio);
           canvas.drawCircle(pointX, pointY, 4, mFaceLandmardkPaint);
       }
       counter++ ;
    }
 }


```

**Comment by nimesh7424** [comment]
Thank you it works in images.

**Comment by kartk** [comment]
In OnGetImageListener.java, onImageAvailable function

**Comment by nimesh7424** [comment]
yes i got it

thank you
