### ISSUE TITLE
Can this APP realize the function of face expression recognition

### ISSUE THREAD

**Issue by momo1986** [gicheonkang/Fast-Face#19]
Hello,
Thanks for yours sharing.
Looks your features of landmark detection is very exciting.
Can I use your APP realize both the function of facial landmark detections and face expression recognition, like, happy, angry and distinguished.
Best Regards!
Jun Yan

**Comment by gicheonkang** [comment]
@momo1986 Hi, sure you can use this source code to develop expression recognition tool. It would be cool :)
