### ISSUE TITLE
How to optimize the jni native code?  

### ISSUE THREAD

**Issue by cmd10** [gicheonkang/Fast-Face#2]
Can you open source your Dlib-android source code ? I want to know how to optimize it and make it faster, thank you!!!

**Comment by gicheonkang** [comment]
@cmd10 Hi, can you give me your email address ? 
I will send you source code.

**Comment by cmd10** [comment]
@gicheonkang Hi, my email address is 1511044056@qq.com. It is very thanks.

**Comment by gicheonkang** [comment]
Hi, cmd 10. Thank you for your interest !

But, Library is quite large, so I uploaded GitHub repository.

Here is the url<https://github.com/gicheonkang/dlib-android>

I implemented multi-threaded dlib(3 threads are working)


————————— CURRENT ISSUES —————————————

1. Neon Supported dlib
2. Lower the pyramidal layers 


Test and enjoy it !
Regards. CHON

**Comment by zhpengbj** [comment]
@gicheonkang Hi, can you send me your Dlib-android source code? I have the same performance problem too. My email address:81339155@qq.com. Thanks!

**Comment by ldima** [comment]
@gicheonkang Hi,  Could you please give me sources on your Dlib? I want to increase speed. Thanks. 4va2020@gmail.com
