### ISSUE TITLE
why my camera phone didn't showing??

### ISSUE THREAD

**Issue by danielpanda** [gicheonkang/Fast-Face#3]
sir, can you help me. why my camera phone didn't showing anything, it just a black screen.

thankyou very much.
@gicheonkang

**Comment by gicheonkang** [comment]
Hi did u check API level?
It should be at least 19 ! (camera2 library)


2017. 7. 18. 오후 9:06에 "danielpanda" <notifications@github.com>님이 작성:

**Comment by danielpanda** [comment]
@gicheonkang

yes, i did. my API level is 21. my phone android version is lolipop

**Comment by gicheonkang** [comment]
Hmm.. did you wait a few seconds after app had started ? 
In my device, it takes 3 seconds to show camera preview(Initializing camera status).

If it doesn't work, there might be a compatibility issue.
Please Tell me your device info. Thank you so much @danielpanda

**Comment by danielpanda** [comment]
@gicheonkang yes, first time intallation status (copying data) and then showing time cost: (running) but there is just a black screen on the camera preview. i dont know what i must to do.

my device is xiaomi mi4i. api 21, android version 5.0.2.

but, when selecting photo is working correctly. 
your welcome @gicheonkang . me too, thank you so much

**Comment by gicheonkang** [comment]
@danielpanda 
Can you check your camera options just in case it differs from mine.
In app/src/main/.../CameraConnectionFragment.java line 430, You can check the code like below.
`manager.openCamera("1", stateCallback, backgroundHandler);
`
It initialize the camera with selfie mode("1"). Can you modify 1 with 0 ? 
Thanks.

**Comment by danielpanda** [comment]
@gicheonkang 
i'm sorry before, why i got this error[
![image](https://user-images.githubusercontent.com/29721735/28353347-8192e724-6c85-11e7-89f6-000deb2aa30e.png)
](url)
but, i check it with file explorer the files is exist on the folder

and i have modify the code with 0, but nothing changing still black screen on camera preview.
thank you very much CHON.

**Comment by Jacklee12138** [comment]
hey, how can I change the mix face size   that the detector detects,please

**Comment by gicheonkang** [comment]
#6 may be a reasonable answer. thx.
