### ISSUE TITLE
What are the methods behind your Fast-Face?

### ISSUE THREAD

**Issue by lzwhard** [gicheonkang/Fast-Face#7]
tks

**Comment by gicheonkang** [comment]
Hi @Izwhard. Thank you for your interest.
This app extracts a features, and then pointing out  some landmark points.
It is required to use Dlib library(deep learning based open source).

**Comment by lzwhard** [comment]
Hi gicheonkang,
Thank you for your reply. May I have the paper you refered to?

**Comment by gicheonkang** [comment]
@lzwhard 
what paper do you mean?
I developed the code from dlib-android.
Here is the url of source code
https://github.com/tzutalin/dlib-android

If you have any questions, feel free to reopen it. 
Thank you so much.
