### ISSUE TITLE
How can I detect the middle of the forehead?

### ISSUE THREAD

**Issue by arisprung** [gicheonkang/Fast-Face#8]
How can I detect the middle of the forehead?

I don't see and landmarks to detect this...Any idea?

**Comment by gicheonkang** [comment]
Hi, @arisprung 
Thank you for your interest.

Honestly, If you want to detect a forehead detector, you need to make a customized model(deep learning based).
But, It it not easy to get a datasets that have a middle of the forehead.

So, I think making a algorithm is the reasonable way.
Algorithm is simple. Inter-ocular coordinates (x, y) + alpha(orthogonal line).

If you have any idea, please reply this message. Let's think about it together.
Thank you so much. 👍
